### ISSUE TITLE
Example of 3D

### ISSUE THREAD

**Issue by David-OConnor** [virtualritz/uniform-cubic-splines#1]
Hi! This crate looks great! Is There an example of using it to interpolate on a 3D grid of f64s, using a polynomial (eg quadratic) interpolation? Thank you! Ie:

```rust
uniform_cubic_splines::find_value(data: Arr3d, value: f64, order: 2);
```

Thanks!

**Comment by virtualritz** [comment]
As the name of the crate 'suggests', this only deals with *cubic* curves.

Curves of other degree, e.g. quadratic, are not supported.
 
I do not understand what your question is. There is no `find_value()` function in this crate and there won't be, the crate is complete as-is. For more info see the [OSL spec.](https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/main/src/doc/osl-languagespec.pdf), pp 59.

You can interpolate any type that implements the trait bounds the resp. function requires. E.g. [`cgmath::Vector3`](https://docs.rs/cgmath/latest/cgmath/struct.Vector3.html).

```rust
use cgmath::Vector3;
use uniform_cubic_splines::{basis::CatmullRom, spline};

type DVec3 = Vector3<f64>;

fn main() {
    // We want to evaluate the spline at knot value 0.5.
    let v = 0.5;

    // The first and last points are never interpolated.
    let knots = [
        DVec3::new(0.0, 0.0, 0.0),
        DVec3::new(0.0, 0.0, 0.0),
        DVec3::new(1.0, 2.0, 3.0),
        DVec3::new(2.0, 1.0, 2.0),
        DVec3::new(3.0, 3.0, 1.0),
        DVec3::new(3.0, 3.0, 1.0),
    ];

    let y = spline::<CatmullRom, _, _>(v, &knots);

    println!("Value at {v} is {:?}.", y);
}
```

This prints:
```
Value at 0.5 is Vector3 [1.5, 1.5, 2.75].
```

**Comment by virtualritz** [comment]
Closing this for now. Feel free to reopen if I didn't answer your question.

If you think a feature is missing, please open a new issue.
